// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc.proto

#include "rpc.pb.h"
#include "rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace plasmaRPC {

static const char* RemoteObjectShare_method_names[] = {
  "/plasmaRPC.RemoteObjectShare/GetObjects",
};

std::unique_ptr< RemoteObjectShare::Stub> RemoteObjectShare::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RemoteObjectShare::Stub> stub(new RemoteObjectShare::Stub(channel, options));
  return stub;
}

RemoteObjectShare::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetObjects_(RemoteObjectShare_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RemoteObjectShare::Stub::GetObjects(::grpc::ClientContext* context, const ::plasmaRPC::ObjectIDs& request, ::plasmaRPC::ObjectDetailsList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::plasmaRPC::ObjectIDs, ::plasmaRPC::ObjectDetailsList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetObjects_, context, request, response);
}

void RemoteObjectShare::Stub::experimental_async::GetObjects(::grpc::ClientContext* context, const ::plasmaRPC::ObjectIDs* request, ::plasmaRPC::ObjectDetailsList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::plasmaRPC::ObjectIDs, ::plasmaRPC::ObjectDetailsList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetObjects_, context, request, response, std::move(f));
}

void RemoteObjectShare::Stub::experimental_async::GetObjects(::grpc::ClientContext* context, const ::plasmaRPC::ObjectIDs* request, ::plasmaRPC::ObjectDetailsList* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::plasmaRPC::ObjectDetailsList>* RemoteObjectShare::Stub::PrepareAsyncGetObjectsRaw(::grpc::ClientContext* context, const ::plasmaRPC::ObjectIDs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::plasmaRPC::ObjectDetailsList, ::plasmaRPC::ObjectIDs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetObjects_, context, request);
}

::grpc::ClientAsyncResponseReader< ::plasmaRPC::ObjectDetailsList>* RemoteObjectShare::Stub::AsyncGetObjectsRaw(::grpc::ClientContext* context, const ::plasmaRPC::ObjectIDs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetObjectsRaw(context, request, cq);
  result->StartCall();
  return result;
}

RemoteObjectShare::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RemoteObjectShare_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RemoteObjectShare::Service, ::plasmaRPC::ObjectIDs, ::plasmaRPC::ObjectDetailsList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RemoteObjectShare::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plasmaRPC::ObjectIDs* req,
             ::plasmaRPC::ObjectDetailsList* resp) {
               return service->GetObjects(ctx, req, resp);
             }, this)));
}

RemoteObjectShare::Service::~Service() {
}

::grpc::Status RemoteObjectShare::Service::GetObjects(::grpc::ServerContext* context, const ::plasmaRPC::ObjectIDs* request, ::plasmaRPC::ObjectDetailsList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace plasmaRPC

